title: TimVideos Planet - Developers news
description: "News from our best developers, all news aggregated by planet."
url: "http://planet.timvideos.us"
exclude: [Gemfile, Gemfile.lock, planet.yml, README.md]

markdown: kramdown
permalink: pretty
